# .github/workflows/main.yml
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DB_NAME: test_db
  DB_USER: test_user
  DB_PASS: test_pass

jobs:
  run-code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'CREATE USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASS}}";' -uroot -proot
          sudo mysql -e 'GRANT ALL PRIVILEGES ON ${{env.DB_NAME}}.* TO "${{env.DB_USER}}"@"localhost";' -uroot -proot
          sudo mysql -e 'FLUSH PRIVILEGES;'
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};'' -u${{env.DB_USER}} -p${{env.DB_PASS}}

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout Code Repo
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...

      - name: Run Tests
        run: go test